### PR TITLE
AdamQQPlotPullReq

### PR DESCRIPTION
**Pull request by adpoleski1**

### CODE REVIEW

**Comment by Qiaojuan-Tu** [comment]
In the Overview Page, the last bullet instruction's first letter should be capitalized. The rest looks all good.

**Review by Qiaojuan-Tu — COMMENTED** [review]
Other than capitalized the last instruction on the overview page. The rest looks all good to me.

**Comment by neilhatfield** [comment]
@adpoleski1 
I've reopened the pull request and re-assigned reviewers. Once @paridhi1603 and @Qiaojuan-Tu have clicked "Approve" on their reviews, re-assign this repo to me for final processing.
@Qiaojuan-Tu Feel free to just double check that the issue you saw last time is fixed and then in your Review click "Approve".

**Comment by paridhi1603** [comment]
Looks great to me!

**Review by paridhi1603 — DISMISSED** [review]

**Review by Qiaojuan-Tu — DISMISSED** [review]
Everything looks good to me.

**Review by neilhatfield — CHANGES_REQUESTED** [review]
@adpoleski1  Here are some things that need cleaning up:

1. Make a `docs` folder and move both LICENSE.md and README.md into that folder
2. Delete extraneous files
    + At the top level of repo: Xui.R, Xserver.R, ui.R, server.R, manifest.json
    + In the `www`, all three files may be deleted
3. Changes to README.md
    + Move to the `docs` folder as mentioned
    + Change the life cycle badge from questioning to experimental
4. Changes to the DESCRIPTION file
    + I think that you qualify for the author (aut) role, but not the creator (cre) role
    + Where did the learning objectives listed come from?
    + Put a comma at the end of line 6
    + Remove the comma at the end of line 7
    + Remove the blank line at line 8
5. Changes to app.R
    + Remove any extraneous library calls (e.g., `plotrix`, `reshape2`, `scales`, `dplyr`, `formattable`, `truncnorm`)
    + Add `width = 250` as the first argument of `dashboardSidebar` (this accidentally got left out of the template and is needed)
    + `strong` does not need to be used in conjunction with *any* header tags (i.e., `h1`, `h2`, etc.) Remove all such instances.
    + Only the list items themselves (i.e., `tags$li`) need to be inside of either `tags$ul` or `tags$ol`. The headers do not. (See line 56; move line to outside of the list environment)
    + Watch out for long lines of code (e.g., line 57); break lines that are more than 80 characters
    + Please add a semi-colon just after 'center' and before the double-quotation mark in line 66
    + You're missing the last update line of text on the Overview page.
    + Reduce the number of breaks (`br()`) on the Prereq's page to zero
    + Change the `h4` to `h3` for the "QQ Plot Example" (line 107)--you're skipping heading levels otherwise (accessibility issue)
    + Example Plots--Change their titles so that they are clearly marked as to whether or not the data are consistent with a Normal/Gaussian distribution
    + I would encourage you to change the names (`plotnorm3` and `plotleft3`--which is on the right?) to be more meaningful
    + For __*ALL*__ plots, you must include meaningful alt text; the default of "Plot object" is NOT sufficient. This can be set with the `alt` argument of `renderPlot`.
    + Remove extraneous empty lines throughout your code (no more one between different blocks of code).
    + Make all code explicit by naming the arguments (e.g., line 152)--this applies to the entire R file
    + Re-indent all code to improve readability (e.g., line 165)--applies to all code
    + There should be three breaks (`br()`) between the last reference and the `boastUtils::copyrightInfo()` call.
    + Feel free to make jump points to help highlight sections of your code (Make a comment in the code and then end the line with four dashes)
    + Remove the colons from the labels on the sliders for the different types of distributions (e.g., "Skewness:")
    + Why does the `observeEvent` that starts on line 433 not close until line 1247? This feels excessive and points to inefficient coding.
    + Our default plotting theme is `theme_bw()` for `ggplot`. Please use this.
    + I find the light blue points for the second path harder to see. Consider changing the color. Related: I would use three non-black colors for the various paths
    + I'm not sold on the use of `EnvStats::qqPlot`. I think that there are better approaches such as `car::qqPlot` which are a bit easier to run, allow for the use of formula and groups, as well as adding in a confidence envelope.
    + Why are we standardizing the data for these plots? We don't have to do so.
    + Since the reference distribution is always the Gaussian ("normal"), all of the plotting code for the QQ plot on the Explore page can be reduced to a single instance. That instance will draw from a data set (potentially set up as an `eventReactive`) which adapts to fit the needs/specifications of the user.

I'm going to stop here as these changes will keep you busy for awhile.

**Review by YudanZhang — DISMISSED** [review]

**Review by JingFu1 — CHANGES_REQUESTED** [review]
Unaddressed Github issues: 
1.instruction needed
2. redundant list
3. wrong instructions information: 'There are five types of population types you can choose: left-skewed, right-skewed, symmetric, bimodel, and normal (Gaussian).' --- users can’t choose normal population

Recommended Priority: High

**Pull request merged**
